// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package interactive

import (
	"context"
	"github.com/StarJoice/tech_blog/internal/interactive/internal/event"
	"github.com/StarJoice/tech_blog/internal/interactive/internal/repository"
	"github.com/StarJoice/tech_blog/internal/interactive/internal/repository/dao"
	"github.com/StarJoice/tech_blog/internal/interactive/internal/service"
	"github.com/StarJoice/tech_blog/internal/interactive/internal/web"
	"github.com/ecodeclub/mq-api"
	"github.com/ego-component/egorm"
	"github.com/google/wire"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitModule(db *gorm.DB, q mq.MQ) (*Module, error) {
	interactiveDao := InitDao(db)
	repositoryRepository := repository.NewInteractiveRepository(interactiveDao)
	serviceService := service.NewInteractiveService(repositoryRepository)
	handler := web.NewHandler(serviceService)
	consumer := initConsumer(serviceService, q)
	module := &Module{
		Hdl: handler,
		Svc: serviceService,
		c:   consumer,
	}
	return module, nil
}

// wire.go:

var ProviderSet = wire.NewSet(web.NewHandler, service.NewInteractiveService, repository.NewInteractiveRepository, InitDao)

func InitDao(db *egorm.Component) dao.InteractiveDao {
	err := dao.InitTable(db)
	if err != nil {
		panic(err)
	}
	return dao.NewInteractiveGormDao(db)
}

func initConsumer(svc service.Service, q mq.MQ) *event.Consumer {
	consumer, err := event.NewSyncConsumer(svc, q)
	if err != nil {
		panic(err)
	}
	consumer.Start(context.Background())
	return consumer
}
