// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package article

import (
	"github.com/StarJoice/tech_blog/internal/article/repository"
	"github.com/StarJoice/tech_blog/internal/article/repository/dao"
	"github.com/StarJoice/tech_blog/internal/article/service"
	"github.com/StarJoice/tech_blog/internal/article/web"
	"github.com/ego-component/egorm"
	"github.com/google/wire"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitHandler(db *gorm.DB) *web.ArticleHandler {
	articleDao := InitDao(db)
	articleRepository := repository.NewArticleCachedRepository(articleDao)
	articleService := service.NewArticleSvc(articleRepository)
	articleHandler := web.NewArticleHandler(articleService)
	return articleHandler
}

// wire.go:

var ProviderSet = wire.NewSet(web.NewArticleHandler, repository.NewArticleCachedRepository, service.NewArticleSvc, InitDao)

func InitDao(db *egorm.Component) dao.ArticleDao {
	err := dao.InitTable(db)
	if err != nil {
		panic(err)
	}
	return dao.NewArticleGormDao(db)
}

type Handler = web.ArticleHandler
