definitions:
  web.Result:
    description: 该结构体描述了 API 请求的返回格式
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
  web.loginReq:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
info:
  contact: {}
paths:
  /login:
    post:
      consumes:
      - application/json
      description: 用户通过邮箱和密码登录，如果成功，则生成会话（Session）
      parameters:
      - description: 登录请求
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/web.loginReq'
      produces:
      - application/json
      responses:
        "200":
          description: 登录成功"  // 使用手动描述的 web.Result 类型
          schema:
            $ref: '#/definitions/web.Result'
        "400":
          description: 邮箱或密码错误
          schema:
            $ref: '#/definitions/web.Result'
        "500":
          description: 系统错误
          schema:
            $ref: '#/definitions/web.Result'
      summary: 用户登录
      tags:
      - user
swagger: "2.0"
